2015-08-17 15:26:41(pid=6904,tid=598) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-17 15:26:41(pid=6904,tid=605) : TalkApi.request (D) : fetchOps[localRev=16,count=100,globalRev=33872,individualRev=0]
2015-08-17 15:26:42(pid=6904,tid=598) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_updateNotificationToken(TalkService.java:14627)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-17 15:26:42(pid=6904,tid=598) : TalkApi.request (D) : getProfileWithoutHandleException[]
2015-08-17 15:26:42(pid=6904,tid=606) : TalkApi.exception (D) : RequestCallback[1](elapseTime=384ms)
jp.naver.line.android.thrift.TTransportResetConnectionException: jp.naver.line.android.legy.LegyResetConnectionException
	at jp.naver.line.android.thrift.LineTTransport.convertToTTransportException(LineTTransport.java:609)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:486)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)
Caused by: jp.naver.line.android.legy.LegyResetConnectionException
	at jp.naver.line.android.legy.spdy.LegySpdyChannelHandler.resetMember(LegySpdyChannelHandler.java:453)
	at jp.naver.line.android.legy.spdy.LegySpdySession$LegySpdyChannelPipelineFactory.resetMember(LegySpdySession.java:500)
	at jp.naver.line.android.legy.spdy.LegySpdySession.resetMember(LegySpdySession.java:86)
	at jp.naver.line.android.legy.LegySession.close(LegySession.java:358)
	at jp.naver.line.android.legy.LegySessionPool$CachedLegySession.closeSession(LegySessionPool.java:290)
	at jp.naver.line.android.legy.LegySessionPool.closeSpdySessions(LegySessionPool.java:105)
	at jp.naver.line.android.legy.LegySessionPool.closeAllSessions(LegySessionPool.java:41)
	at jp.naver.line.android.thrift.client.TalkClient.handleTalkException(TalkClient.java:124)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6198)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	... 1 more

2015-08-17 15:26:42(pid=6904,tid=588) : TalkApi.request (D) : fetchOps[localRev=16,count=100,globalRev=33872,individualRev=0]
2015-08-17 15:26:42(pid=6904,tid=594) : TalkApi.exception (D) : RequestCallback[2](elapseTime=425ms)
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_getProfile(TalkService.java:5518)
	at jp.naver.line.android.thrift.client.TalkServiceClient$2.getResponse(TalkServiceClient.java:2801)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:134)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)

2015-08-17 15:26:42(pid=6904,tid=608) : TalkApi.exception (D) : RequestCallback[3](elapseTime=224ms)
jp.naver.line.android.thrift.TTransportResetConnectionException: jp.naver.line.android.legy.LegyResetConnectionException
	at jp.naver.line.android.thrift.LineTTransport.convertToTTransportException(LineTTransport.java:609)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:486)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)
Caused by: jp.naver.line.android.legy.LegyResetConnectionException
	at jp.naver.line.android.legy.spdy.LegySpdyChannelHandler.resetMember(LegySpdyChannelHandler.java:453)
	at jp.naver.line.android.legy.spdy.LegySpdySession$LegySpdyChannelPipelineFactory.resetMember(LegySpdySession.java:500)
	at jp.naver.line.android.legy.spdy.LegySpdySession.resetMember(LegySpdySession.java:86)
	at jp.naver.line.android.legy.LegySession.close(LegySession.java:358)
	at jp.naver.line.android.legy.LegySessionPool$CachedLegySession.closeSession(LegySessionPool.java:290)
	at jp.naver.line.android.legy.LegySessionPool.closeSpdySessions(LegySessionPool.java:105)
	at jp.naver.line.android.legy.LegySessionPool.closeAllSessions(LegySessionPool.java:41)
	at jp.naver.line.android.thrift.client.TalkClient$GetProfileCallback.failed(TalkClient.java:177)
	at jp.naver.line.android.thrift.client.TalkServiceClient$2.innerFailed(TalkServiceClient.java:2821)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:137)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	... 10 more

2015-08-17 15:54:20(pid=11656,tid=910) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-17 15:54:20(pid=11656,tid=910) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-17 15:54:28(pid=11656,tid=910) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-17 15:54:28(pid=11656,tid=910) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-17 15:54:52(pid=11656,tid=926) : TalkApi.request (D) : notifyUpdated[lastRev=16,deviceInfo=DeviceInfo(applicationType:ANDROID_BETA, deviceName:SHV-E300S, systemName:Android OS, systemVersion:4.3, model:SHV-E300S, carrierCode:NOT_SPECIFIED, carrierName:45005)]
2015-08-17 15:54:52(pid=11656,tid=926) : TalkApi.exception (D) : notifyUpdated
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.notifyUpdated(TalkServiceClient.java:3941)
	at jp.naver.line.android.DeviceInfoUpdater$1.run(DeviceInfoUpdater.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-17 15:55:06(pid=11656,tid=910) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-17 15:55:06(pid=11656,tid=910) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-17 15:58:44(pid=11656,tid=910) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-17 15:58:44(pid=11656,tid=910) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-17 16:20:22(pid=11656,tid=910) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-17 16:20:22(pid=11656,tid=910) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-17 18:06:33(pid=23544,tid=1180) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-17 18:06:33(pid=23544,tid=1180) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-17 18:06:41(pid=23544,tid=1180) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-17 18:06:41(pid=23544,tid=1180) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-17 18:56:12(pid=23544,tid=1197) : TalkApi.request (D) : notifyUpdated[lastRev=16,deviceInfo=DeviceInfo(applicationType:ANDROID_BETA, deviceName:SHV-E300S, systemName:Android OS, systemVersion:4.3, model:SHV-E300S, carrierCode:NOT_SPECIFIED, carrierName:45005)]
2015-08-17 18:56:13(pid=23544,tid=1170) : TalkApi.request (D) : getProfileWithoutHandleException[]
2015-08-17 18:56:13(pid=23544,tid=1170) : TalkApi.exception (D) : RequestCallback[recv_notifyUpdated, 2](elapseTime=940ms)
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_notifyUpdated(TalkService.java:5383)
	at jp.naver.line.android.thrift.client.TalkServiceClientRequestCallback.getResponse(TalkServiceClientRequestCallback.java:161)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:134)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)

2015-08-17 18:59:57(pid=23544,tid=1177) : TalkApi.exception (D) : RequestCallback[3](elapseTime=224223ms)
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_getProfile(TalkService.java:5518)
	at jp.naver.line.android.thrift.client.TalkServiceClient$2.getResponse(TalkServiceClient.java:2801)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:134)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)

2015-08-17 19:00:07(pid=23544,tid=1180) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-17 19:00:07(pid=23544,tid=1180) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-17 19:14:05(pid=30957,tid=1611) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-17 19:14:05(pid=30957,tid=1611) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-17 19:14:13(pid=30957,tid=1611) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-17 19:14:13(pid=30957,tid=1611) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-17 19:14:38(pid=30957,tid=1628) : TalkApi.request (D) : notifyUpdated[lastRev=16,deviceInfo=DeviceInfo(applicationType:ANDROID_BETA, deviceName:SHV-E300S, systemName:Android OS, systemVersion:4.3, model:SHV-E300S, carrierCode:NOT_SPECIFIED, carrierName:45005)]
2015-08-17 19:14:38(pid=30957,tid=1628) : TalkApi.exception (D) : notifyUpdated
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.notifyUpdated(TalkServiceClient.java:3941)
	at jp.naver.line.android.DeviceInfoUpdater$1.run(DeviceInfoUpdater.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-17 19:14:51(pid=30957,tid=1611) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-17 19:14:51(pid=30957,tid=1611) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-17 19:18:29(pid=30957,tid=1611) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-17 19:18:29(pid=30957,tid=1611) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

