2015-08-20 10:05:07(pid=3036,tid=13072) : TalkApi.request (D) : fetchOps[localRev=16,count=100,globalRev=33872,individualRev=0]
2015-08-20 10:05:08(pid=3036,tid=13069) : TalkApi.request (D) : getProfileWithoutHandleException[]
2015-08-20 10:05:08(pid=3036,tid=13069) : TalkApi.exception (D) : RequestCallback[0](elapseTime=501ms)
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_fetchOps(TalkService.java:10514)
	at jp.naver.line.android.thrift.client.TalkServiceClient$1.getResponse(TalkServiceClient.java:1064)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:134)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 10:05:09(pid=3036,tid=13070) : TalkApi.request (D) : fetchOps[localRev=16,count=100,globalRev=33872,individualRev=0]
2015-08-20 10:05:09(pid=3036,tid=13065) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-20 10:05:11(pid=3036,tid=13072) : TalkApi.exception (D) : RequestCallback[2](elapseTime=2271ms)
jp.naver.line.android.thrift.TTransportResetConnectionException: jp.naver.line.android.legy.LegyResetConnectionException: received GoAwayFrame.
	at jp.naver.line.android.thrift.LineTTransport.convertToTTransportException(LineTTransport.java:609)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:486)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)
Caused by: jp.naver.line.android.legy.LegyResetConnectionException: received GoAwayFrame.
	at jp.naver.line.android.legy.spdy.LegySpdyChannelHandler.messageReceived(LegySpdyChannelHandler.java:374)
	at jp.naver.line.android.legy.spdy.LegySpdyLoggingHandler.messageReceived(LegySpdyLoggingHandler.java:52)
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:148)
	at org.jboss.netty.handler.codec.spdy.SpdySessionHandler.messageReceived(SpdySessionHandler.java:399)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:423)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:404)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:268)
	at jp.naver.line.android.legy.spdy.LegySpdyFrameCodec.handleUpstream(LegySpdyFrameCodec.java:27)
	at org.jboss.netty.handler.timeout.ReadTimeoutHandler.messageReceived(ReadTimeoutHandler.java:198)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.oio.OioWorker.process(OioWorker.java:96)
	at org.jboss.netty.channel.socket.oio.AbstractOioWorker.run(AbstractOioWorker.java:82)
	at org.jboss.netty.channel.socket.oio.OioWorker.run(OioWorker.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	... 1 more

2015-08-20 10:05:11(pid=3036,tid=13065) : TalkApi.exception (D) : updateNotificationToken
org.apache.thrift.transport.TTransportException: org.jboss.netty.handler.codec.spdy.SpdyProtocolException
	at jp.naver.line.android.thrift.LineTTransport.convertToTTransportException(LineTTransport.java:619)
	at jp.naver.line.android.thrift.LineTTransport.innerFlush(LineTTransport.java:366)
	at jp.naver.line.android.thrift.LineTTransport.flush(LineTTransport.java:324)
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.send_updateNotificationToken(TalkService.java:14601)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)
Caused by: org.jboss.netty.handler.codec.spdy.SpdyProtocolException
	at org.jboss.netty.handler.codec.spdy.SpdySessionHandler.<clinit>(SpdySessionHandler.java:43)
	at jp.naver.line.android.legy.spdy.LegySpdySession$LegySpdyChannelPipelineFactory.getPipeline(LegySpdySession.java:458)
	at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:207)
	at jp.naver.line.android.legy.LegySession$ConnectFuture.startConnect(LegySession.java:186)
	at jp.naver.line.android.legy.LegySession.connect(LegySession.java:325)
	at jp.naver.line.android.legy.LegySessionChecker.checkConnection(LegySessionChecker.java:183)
	at jp.naver.line.android.legy.LegySessionManager$RequestRunnable.innerRun(LegySessionManager.java:177)
	at jp.naver.line.android.util.ExecutorsUtils$SafeRunnable.run(ExecutorsUtils.java:341)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	... 1 more

2015-08-20 10:05:14(pid=3036,tid=13072) : TalkApi.request (D) : fetchOps[localRev=16,count=100,globalRev=33872,individualRev=0]
2015-08-20 10:05:14(pid=3036,tid=13072) : TalkApi.exception (D) : RequestCallback[1](elapseTime=6660ms)
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_getProfile(TalkService.java:5518)
	at jp.naver.line.android.thrift.client.TalkServiceClient$2.getResponse(TalkServiceClient.java:2801)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:134)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 10:05:14(pid=3036,tid=13069) : TalkApi.exception (D) : RequestCallback[4](elapseTime=331ms)
jp.naver.line.android.thrift.TTransportResetConnectionException: jp.naver.line.android.legy.LegyResetConnectionException
	at jp.naver.line.android.thrift.LineTTransport.convertToTTransportException(LineTTransport.java:609)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:486)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)
Caused by: jp.naver.line.android.legy.LegyResetConnectionException
	at jp.naver.line.android.legy.spdy.LegySpdyChannelHandler.resetMember(LegySpdyChannelHandler.java:453)
	at jp.naver.line.android.legy.spdy.LegySpdySession$LegySpdyChannelPipelineFactory.resetMember(LegySpdySession.java:500)
	at jp.naver.line.android.legy.spdy.LegySpdySession.resetMember(LegySpdySession.java:86)
	at jp.naver.line.android.legy.LegySession.close(LegySession.java:358)
	at jp.naver.line.android.legy.LegySessionPool$CachedLegySession.closeSession(LegySessionPool.java:290)
	at jp.naver.line.android.legy.LegySessionPool.closeSpdySessions(LegySessionPool.java:105)
	at jp.naver.line.android.legy.LegySessionPool.closeAllSessions(LegySessionPool.java:41)
	at jp.naver.line.android.thrift.client.TalkClient$GetProfileCallback.failed(TalkClient.java:177)
	at jp.naver.line.android.thrift.client.TalkServiceClient$2.innerFailed(TalkServiceClient.java:2821)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:137)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	... 10 more

2015-08-20 10:05:19(pid=3036,tid=13065) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-20 10:05:19(pid=3036,tid=13065) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 10:05:42(pid=3036,tid=13087) : TalkApi.request (D) : notifyUpdated[lastRev=16,deviceInfo=DeviceInfo(applicationType:ANDROID_BETA, deviceName:SHV-E300S, systemName:Android OS, systemVersion:4.3, model:SHV-E300S, carrierCode:NOT_SPECIFIED, carrierName:45005)]
2015-08-20 10:05:42(pid=3036,tid=13087) : TalkApi.exception (D) : notifyUpdated
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.notifyUpdated(TalkServiceClient.java:3941)
	at jp.naver.line.android.DeviceInfoUpdater$1.run(DeviceInfoUpdater.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 10:05:57(pid=3036,tid=13065) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-20 10:05:57(pid=3036,tid=13065) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 11:12:25(pid=5080,tid=13236) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-20 11:12:25(pid=5080,tid=13236) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 11:12:33(pid=5080,tid=13236) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-20 11:12:33(pid=5080,tid=13236) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 11:12:57(pid=5080,tid=13253) : TalkApi.request (D) : notifyUpdated[lastRev=16,deviceInfo=DeviceInfo(applicationType:ANDROID_BETA, deviceName:SHV-E300S, systemName:Android OS, systemVersion:4.3, model:SHV-E300S, carrierCode:NOT_SPECIFIED, carrierName:45005)]
2015-08-20 11:12:57(pid=5080,tid=13253) : TalkApi.exception (D) : notifyUpdated
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.notifyUpdated(TalkServiceClient.java:3941)
	at jp.naver.line.android.DeviceInfoUpdater$1.run(DeviceInfoUpdater.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 11:13:11(pid=5080,tid=13236) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-20 11:13:11(pid=5080,tid=13236) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 11:16:49(pid=5080,tid=13236) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-20 11:16:49(pid=5080,tid=13236) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 12:09:20(pid=13122,tid=13684) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-20 12:09:20(pid=13122,tid=13684) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 12:09:28(pid=13122,tid=13684) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-20 12:09:28(pid=13122,tid=13684) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 12:09:53(pid=13122,tid=13701) : TalkApi.request (D) : notifyUpdated[lastRev=16,deviceInfo=DeviceInfo(applicationType:ANDROID_BETA, deviceName:SHV-E300S, systemName:Android OS, systemVersion:4.3, model:SHV-E300S, carrierCode:NOT_SPECIFIED, carrierName:45005)]
2015-08-20 12:09:53(pid=13122,tid=13701) : TalkApi.exception (D) : notifyUpdated
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.notifyUpdated(TalkServiceClient.java:3941)
	at jp.naver.line.android.DeviceInfoUpdater$1.run(DeviceInfoUpdater.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 12:10:06(pid=13122,tid=13684) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-20 12:10:06(pid=13122,tid=13684) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 12:13:44(pid=13122,tid=13684) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-20 12:13:44(pid=13122,tid=13684) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 12:35:22(pid=13122,tid=13684) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-20 12:35:22(pid=13122,tid=13684) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 13:19:00(pid=13122,tid=13689) : TalkApi.request (D) : fetchOps[localRev=16,count=100,globalRev=33872,individualRev=0]
2015-08-20 13:19:01(pid=13122,tid=13688) : TalkApi.request (D) : getProfileWithoutHandleException[]
2015-08-20 13:19:01(pid=13122,tid=13688) : TalkApi.exception (D) : RequestCallback[6](elapseTime=1091ms)
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_fetchOps(TalkService.java:10514)
	at jp.naver.line.android.thrift.client.TalkServiceClient$1.getResponse(TalkServiceClient.java:1064)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:134)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 13:19:01(pid=13122,tid=13675) : TalkApi.request (D) : fetchOps[localRev=16,count=100,globalRev=33872,individualRev=0]
2015-08-20 13:19:05(pid=13122,tid=13688) : TalkApi.exception (D) : RequestCallback[8](elapseTime=3223ms)
jp.naver.line.android.thrift.TTransportResetConnectionException: jp.naver.line.android.legy.LegyResetConnectionException
	at jp.naver.line.android.thrift.LineTTransport.convertToTTransportException(LineTTransport.java:609)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:486)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)
Caused by: jp.naver.line.android.legy.LegyResetConnectionException
	at jp.naver.line.android.legy.spdy.LegySpdyChannelHandler.resetMember(LegySpdyChannelHandler.java:453)
	at jp.naver.line.android.legy.spdy.LegySpdySession$LegySpdyChannelPipelineFactory.resetMember(LegySpdySession.java:500)
	at jp.naver.line.android.legy.spdy.LegySpdySession.resetMember(LegySpdySession.java:86)
	at jp.naver.line.android.legy.LegySession.close(LegySession.java:358)
	at jp.naver.line.android.legy.LegySessionPool$CachedLegySession.closeSession(LegySessionPool.java:290)
	at jp.naver.line.android.legy.LegySessionPool.closeSpdySessions(LegySessionPool.java:105)
	at jp.naver.line.android.legy.LegySessionPool.closeAllSessions(LegySessionPool.java:41)
	at jp.naver.line.android.thrift.client.TalkClient$GetProfileCallback.failed(TalkClient.java:177)
	at jp.naver.line.android.thrift.client.TalkServiceClient$2.innerFailed(TalkServiceClient.java:2821)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:137)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	... 10 more

2015-08-20 13:19:05(pid=13122,tid=13690) : TalkApi.exception (D) : RequestCallback[7](elapseTime=3512ms)
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_getProfile(TalkService.java:5518)
	at jp.naver.line.android.thrift.client.TalkServiceClient$2.getResponse(TalkServiceClient.java:2801)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:134)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 15:18:17(pid=2251,tid=13986) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-20 15:18:17(pid=2251,tid=13986) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 15:18:25(pid=2251,tid=13986) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-20 15:18:25(pid=2251,tid=13986) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 15:18:45(pid=2251,tid=14004) : TalkApi.request (D) : notifyUpdated[lastRev=16,deviceInfo=DeviceInfo(applicationType:ANDROID_BETA, deviceName:SHV-E300S, systemName:Android OS, systemVersion:4.3, model:SHV-E300S, carrierCode:NOT_SPECIFIED, carrierName:45005)]
2015-08-20 15:18:45(pid=2251,tid=14004) : TalkApi.exception (D) : notifyUpdated
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.notifyUpdated(TalkServiceClient.java:3941)
	at jp.naver.line.android.DeviceInfoUpdater$1.run(DeviceInfoUpdater.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 15:19:03(pid=2251,tid=13986) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-20 15:19:03(pid=2251,tid=13986) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 15:22:41(pid=2251,tid=13986) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-20 15:22:41(pid=2251,tid=13986) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 15:44:19(pid=2251,tid=13986) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-20 15:44:19(pid=2251,tid=13986) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 16:26:17(pid=2251,tid=13992) : TalkApi.request (D) : fetchOps[localRev=16,count=100,globalRev=33872,individualRev=0]
2015-08-20 16:26:19(pid=2251,tid=13984) : TalkApi.request (D) : getProfileWithoutHandleException[]
2015-08-20 16:26:19(pid=2251,tid=13984) : TalkApi.exception (D) : RequestCallback[6](elapseTime=1824ms)
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_fetchOps(TalkService.java:10514)
	at jp.naver.line.android.thrift.client.TalkServiceClient$1.getResponse(TalkServiceClient.java:1064)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:134)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 16:26:21(pid=2251,tid=13994) : TalkApi.request (D) : fetchOps[localRev=16,count=100,globalRev=33872,individualRev=0]
2015-08-20 16:26:23(pid=2251,tid=13984) : TalkApi.exception (D) : RequestCallback[7](elapseTime=3477ms)
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_getProfile(TalkService.java:5518)
	at jp.naver.line.android.thrift.client.TalkServiceClient$2.getResponse(TalkServiceClient.java:2801)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:134)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)

2015-08-20 16:26:23(pid=2251,tid=13977) : TalkApi.exception (D) : RequestCallback[8](elapseTime=2186ms)
jp.naver.line.android.thrift.TTransportResetConnectionException: jp.naver.line.android.legy.LegyResetConnectionException
	at jp.naver.line.android.thrift.LineTTransport.convertToTTransportException(LineTTransport.java:609)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:486)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)
Caused by: jp.naver.line.android.legy.LegyResetConnectionException
	at jp.naver.line.android.legy.spdy.LegySpdyChannelHandler.resetMember(LegySpdyChannelHandler.java:453)
	at jp.naver.line.android.legy.spdy.LegySpdySession$LegySpdyChannelPipelineFactory.resetMember(LegySpdySession.java:500)
	at jp.naver.line.android.legy.spdy.LegySpdySession.resetMember(LegySpdySession.java:86)
	at jp.naver.line.android.legy.LegySession.close(LegySession.java:358)
	at jp.naver.line.android.legy.LegySessionPool$CachedLegySession.closeSession(LegySessionPool.java:290)
	at jp.naver.line.android.legy.LegySessionPool.closeSpdySessions(LegySessionPool.java:105)
	at jp.naver.line.android.legy.LegySessionPool.closeAllSessions(LegySessionPool.java:41)
	at jp.naver.line.android.thrift.client.TalkClient$GetProfileCallback.failed(TalkClient.java:177)
	at jp.naver.line.android.thrift.client.TalkServiceClient$2.innerFailed(TalkServiceClient.java:2821)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:137)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	... 10 more

