2015-08-19 00:41:36(pid=24098,tid=8682) : TalkApi.request (D) : fetchOps[localRev=16,count=100,globalRev=33872,individualRev=0]
2015-08-19 00:41:37(pid=24098,tid=8682) : TalkApi.request (D) : getProfileWithoutHandleException[]
2015-08-19 00:41:37(pid=24098,tid=8682) : TalkApi.exception (D) : RequestCallback[0](elapseTime=633ms)
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_fetchOps(TalkService.java:10514)
	at jp.naver.line.android.thrift.client.TalkServiceClient$1.getResponse(TalkServiceClient.java:1064)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:134)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 00:41:37(pid=24098,tid=8677) : TalkApi.request (D) : fetchOps[localRev=16,count=100,globalRev=33872,individualRev=0]
2015-08-19 00:41:39(pid=24098,tid=8680) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 00:41:40(pid=24098,tid=8683) : TalkApi.exception (D) : RequestCallback[2](elapseTime=2711ms)
jp.naver.line.android.thrift.TTransportResetConnectionException: jp.naver.line.android.legy.LegyResetConnectionException
	at jp.naver.line.android.thrift.LineTTransport.convertToTTransportException(LineTTransport.java:609)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:486)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)
Caused by: jp.naver.line.android.legy.LegyResetConnectionException
	at jp.naver.line.android.legy.spdy.LegySpdyChannelHandler.resetMember(LegySpdyChannelHandler.java:453)
	at jp.naver.line.android.legy.spdy.LegySpdySession$LegySpdyChannelPipelineFactory.resetMember(LegySpdySession.java:500)
	at jp.naver.line.android.legy.spdy.LegySpdySession.resetMember(LegySpdySession.java:86)
	at jp.naver.line.android.legy.LegySession.close(LegySession.java:358)
	at jp.naver.line.android.legy.LegySessionPool$CachedLegySession.closeSession(LegySessionPool.java:290)
	at jp.naver.line.android.legy.LegySessionPool.closeSpdySessions(LegySessionPool.java:105)
	at jp.naver.line.android.legy.LegySessionPool.closeAllSessions(LegySessionPool.java:41)
	at jp.naver.line.android.thrift.client.TalkClient$GetProfileCallback.failed(TalkClient.java:177)
	at jp.naver.line.android.thrift.client.TalkServiceClient$2.innerFailed(TalkServiceClient.java:2821)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:137)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	... 10 more

2015-08-19 00:41:40(pid=24098,tid=8677) : TalkApi.exception (D) : RequestCallback[1](elapseTime=3452ms)
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_getProfile(TalkService.java:5518)
	at jp.naver.line.android.thrift.client.TalkServiceClient$2.getResponse(TalkServiceClient.java:2801)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:134)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 00:41:40(pid=24098,tid=8682) : TalkApi.exception (D) : RequestCallback[2](elapseTime=2812ms)
org.apache.thrift.transport.TTransportException: java.nio.channels.ClosedChannelException
	at jp.naver.line.android.thrift.LineTTransport.convertToTTransportException(LineTTransport.java:619)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:486)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.nio.channels.ClosedChannelException
	at org.jboss.netty.channel.socket.oio.OioWorker.write(OioWorker.java:177)
	at org.jboss.netty.channel.socket.oio.OioClientSocketPipelineSink.eventSunk$4b84bdff(OioClientSocketPipelineSink.java:81)
	at org.jboss.netty.channel.Channels.write(Channels.java:733)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:63)
	at org.jboss.netty.handler.codec.spdy.SpdyFrameEncoder.handleDownstream(SpdyFrameEncoder.java:132)
	at jp.naver.line.android.legy.spdy.LegySpdyFrameCodec.handleDownstream(LegySpdyFrameCodec.java:22)
	at org.jboss.netty.handler.codec.spdy.SpdySessionHandler.handleDownstream(SpdySessionHandler.java:636)
	at jp.naver.line.android.legy.spdy.LegySpdySessionHandler.handleDownstream(LegySpdySessionHandler.java:35)
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:295)
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleDownstream(ChunkedWriteHandler.java:127)
	at jp.naver.line.android.legy.spdy.LegySpdyLoggingHandler.writeRequested(LegySpdyLoggingHandler.java:81)
	at org.jboss.netty.channel.Channels.write(Channels.java:733)
	at jp.naver.line.android.legy.spdy.LegySpdyChannelHandler.writeRequested(LegySpdyChannelHandler.java:83)
	at org.jboss.netty.channel.Channels.write(Channels.java:679)
	at jp.naver.line.android.legy.LegySession.write(LegySession.java:485)
	at jp.naver.line.android.legy.LegySession.request(LegySession.java:441)
	at jp.naver.line.android.legy.LegySessionManager$RequestRunnable.innerRun(LegySessionManager.java:180)
	at jp.naver.line.android.util.ExecutorsUtils$SafeRunnable.run(ExecutorsUtils.java:341)
	... 7 more

2015-08-19 00:41:44(pid=24098,tid=8680) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_updateNotificationToken(TalkService.java:14627)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 08:44:00(pid=25734,tid=9662) : TalkApi.request (D) : fetchOps[localRev=16,count=100,globalRev=33872,individualRev=0]
2015-08-19 08:44:01(pid=25734,tid=9662) : TalkApi.request (D) : getProfileWithoutHandleException[]
2015-08-19 08:44:01(pid=25734,tid=9662) : TalkApi.exception (D) : RequestCallback[0](elapseTime=440ms)
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_fetchOps(TalkService.java:10514)
	at jp.naver.line.android.thrift.client.TalkServiceClient$1.getResponse(TalkServiceClient.java:1064)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:134)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 08:44:02(pid=25734,tid=9661) : TalkApi.request (D) : fetchOps[localRev=16,count=100,globalRev=33872,individualRev=0]
2015-08-19 08:44:04(pid=25734,tid=9661) : TalkApi.exception (D) : RequestCallback[1](elapseTime=3550ms)
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_getProfile(TalkService.java:5518)
	at jp.naver.line.android.thrift.client.TalkServiceClient$2.getResponse(TalkServiceClient.java:2801)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:134)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 08:44:04(pid=25734,tid=9653) : TalkApi.exception (D) : RequestCallback[2](elapseTime=1997ms)
jp.naver.line.android.thrift.TTransportResetConnectionException: jp.naver.line.android.legy.LegyResetConnectionException
	at jp.naver.line.android.thrift.LineTTransport.convertToTTransportException(LineTTransport.java:609)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:486)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)
Caused by: jp.naver.line.android.legy.LegyResetConnectionException
	at jp.naver.line.android.legy.spdy.LegySpdyChannelHandler.resetMember(LegySpdyChannelHandler.java:453)
	at jp.naver.line.android.legy.spdy.LegySpdySession$LegySpdyChannelPipelineFactory.resetMember(LegySpdySession.java:500)
	at jp.naver.line.android.legy.spdy.LegySpdySession.resetMember(LegySpdySession.java:86)
	at jp.naver.line.android.legy.LegySession.close(LegySession.java:358)
	at jp.naver.line.android.legy.LegySessionPool$CachedLegySession.closeSession(LegySessionPool.java:290)
	at jp.naver.line.android.legy.LegySessionPool.closeSpdySessions(LegySessionPool.java:105)
	at jp.naver.line.android.legy.LegySessionPool.closeAllSessions(LegySessionPool.java:41)
	at jp.naver.line.android.thrift.client.TalkClient$GetProfileCallback.failed(TalkClient.java:177)
	at jp.naver.line.android.thrift.client.TalkServiceClient$2.innerFailed(TalkServiceClient.java:2821)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:137)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	... 10 more

2015-08-19 08:44:04(pid=25734,tid=9659) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 08:44:04(pid=25734,tid=9659) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 10:06:54(pid=31502,tid=9816) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 10:06:54(pid=31502,tid=9816) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 10:07:02(pid=31502,tid=9816) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 10:07:02(pid=31502,tid=9816) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 10:58:17(pid=7099,tid=9958) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 10:58:17(pid=7099,tid=9958) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 10:58:25(pid=7099,tid=9958) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 10:58:25(pid=7099,tid=9958) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 10:58:50(pid=7099,tid=9974) : TalkApi.request (D) : notifyUpdated[lastRev=16,deviceInfo=DeviceInfo(applicationType:ANDROID_BETA, deviceName:SHV-E300S, systemName:Android OS, systemVersion:4.3, model:SHV-E300S, carrierCode:NOT_SPECIFIED, carrierName:45005)]
2015-08-19 10:58:50(pid=7099,tid=9974) : TalkApi.exception (D) : notifyUpdated
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.notifyUpdated(TalkServiceClient.java:3941)
	at jp.naver.line.android.DeviceInfoUpdater$1.run(DeviceInfoUpdater.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 10:59:03(pid=7099,tid=9958) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 10:59:03(pid=7099,tid=9958) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 11:02:41(pid=7099,tid=9958) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 11:02:41(pid=7099,tid=9958) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 11:24:19(pid=7099,tid=9958) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 11:24:19(pid=7099,tid=9958) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 14:09:27(pid=29478,tid=10340) : TalkApi.request (D) : fetchOps[localRev=16,count=100,globalRev=33872,individualRev=0]
2015-08-19 14:09:27(pid=29478,tid=10347) : TalkApi.request (D) : getProfileWithoutHandleException[]
2015-08-19 14:09:27(pid=29478,tid=10347) : TalkApi.exception (D) : RequestCallback[0](elapseTime=417ms)
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_fetchOps(TalkService.java:10514)
	at jp.naver.line.android.thrift.client.TalkServiceClient$1.getResponse(TalkServiceClient.java:1064)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:134)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 14:09:27(pid=29478,tid=10352) : TalkApi.request (D) : fetchOps[localRev=16,count=100,globalRev=33872,individualRev=0]
2015-08-19 14:09:28(pid=29478,tid=10350) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 14:09:30(pid=29478,tid=10350) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_updateNotificationToken(TalkService.java:14627)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 14:09:30(pid=29478,tid=10356) : TalkApi.exception (D) : RequestCallback[2](elapseTime=3408ms)
jp.naver.line.android.thrift.TTransportResetConnectionException: jp.naver.line.android.legy.LegyResetConnectionException
	at jp.naver.line.android.thrift.LineTTransport.convertToTTransportException(LineTTransport.java:609)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:486)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)
Caused by: jp.naver.line.android.legy.LegyResetConnectionException
	at jp.naver.line.android.legy.spdy.LegySpdyChannelHandler.resetMember(LegySpdyChannelHandler.java:453)
	at jp.naver.line.android.legy.spdy.LegySpdySession$LegySpdyChannelPipelineFactory.resetMember(LegySpdySession.java:500)
	at jp.naver.line.android.legy.spdy.LegySpdySession.resetMember(LegySpdySession.java:86)
	at jp.naver.line.android.legy.LegySession.close(LegySession.java:358)
	at jp.naver.line.android.legy.LegySessionPool$CachedLegySession.closeSession(LegySessionPool.java:290)
	at jp.naver.line.android.legy.LegySessionPool.closeSpdySessions(LegySessionPool.java:105)
	at jp.naver.line.android.legy.LegySessionPool.closeAllSessions(LegySessionPool.java:41)
	at jp.naver.line.android.thrift.client.TalkClient.handleTalkException(TalkClient.java:124)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6198)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	... 1 more

2015-08-19 14:09:31(pid=29478,tid=10356) : TalkApi.exception (D) : RequestCallback[1](elapseTime=3867ms)
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_getProfile(TalkService.java:5518)
	at jp.naver.line.android.thrift.client.TalkServiceClient$2.getResponse(TalkServiceClient.java:2801)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:134)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 14:09:38(pid=29478,tid=10350) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 14:09:38(pid=29478,tid=10350) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 14:10:02(pid=29478,tid=10370) : TalkApi.request (D) : notifyUpdated[lastRev=16,deviceInfo=DeviceInfo(applicationType:ANDROID_BETA, deviceName:SHV-E300S, systemName:Android OS, systemVersion:4.3, model:SHV-E300S, carrierCode:NOT_SPECIFIED, carrierName:45005)]
2015-08-19 14:10:02(pid=29478,tid=10370) : TalkApi.exception (D) : notifyUpdated
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.notifyUpdated(TalkServiceClient.java:3941)
	at jp.naver.line.android.DeviceInfoUpdater$1.run(DeviceInfoUpdater.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 14:10:17(pid=29478,tid=10350) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 14:10:17(pid=29478,tid=10350) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 14:13:55(pid=29478,tid=10350) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 14:13:55(pid=29478,tid=10350) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 15:40:30(pid=1944,tid=10603) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 15:40:30(pid=1944,tid=10603) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 15:40:38(pid=1944,tid=10603) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 15:40:38(pid=1944,tid=10603) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 15:41:03(pid=1944,tid=10621) : TalkApi.request (D) : notifyUpdated[lastRev=16,deviceInfo=DeviceInfo(applicationType:ANDROID_BETA, deviceName:SHV-E300S, systemName:Android OS, systemVersion:4.3, model:SHV-E300S, carrierCode:NOT_SPECIFIED, carrierName:45005)]
2015-08-19 15:41:03(pid=1944,tid=10621) : TalkApi.exception (D) : notifyUpdated
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.notifyUpdated(TalkServiceClient.java:3941)
	at jp.naver.line.android.DeviceInfoUpdater$1.run(DeviceInfoUpdater.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 15:41:16(pid=1944,tid=10603) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 15:41:16(pid=1944,tid=10603) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 15:44:54(pid=1944,tid=10603) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 15:44:54(pid=1944,tid=10603) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 16:48:28(pid=16570,tid=10839) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 16:48:28(pid=16570,tid=10839) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 16:48:36(pid=16570,tid=10839) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 16:48:36(pid=16570,tid=10839) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 16:49:01(pid=16570,tid=10857) : TalkApi.request (D) : notifyUpdated[lastRev=16,deviceInfo=DeviceInfo(applicationType:ANDROID_BETA, deviceName:SHV-E300S, systemName:Android OS, systemVersion:4.3, model:SHV-E300S, carrierCode:NOT_SPECIFIED, carrierName:45005)]
2015-08-19 16:49:01(pid=16570,tid=10857) : TalkApi.exception (D) : notifyUpdated
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.notifyUpdated(TalkServiceClient.java:3941)
	at jp.naver.line.android.DeviceInfoUpdater$1.run(DeviceInfoUpdater.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 16:49:14(pid=16570,tid=10839) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 16:49:14(pid=16570,tid=10839) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 16:52:52(pid=16570,tid=10839) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 16:52:52(pid=16570,tid=10839) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 17:14:30(pid=16570,tid=10839) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 17:14:31(pid=16570,tid=10839) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_updateNotificationToken(TalkService.java:14627)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 17:14:31(pid=16570,tid=10839) : TalkApi.request (D) : getProfileWithoutHandleException[]
2015-08-19 17:14:34(pid=16570,tid=10843) : TalkApi.exception (D) : RequestCallback[6](elapseTime=3376ms)
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_getProfile(TalkService.java:5518)
	at jp.naver.line.android.thrift.client.TalkServiceClient$2.getResponse(TalkServiceClient.java:2801)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:134)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 19:55:33(pid=8149,tid=11277) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 19:55:33(pid=8149,tid=11277) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 19:55:41(pid=8149,tid=11277) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 19:55:41(pid=8149,tid=11277) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 19:56:06(pid=8149,tid=11295) : TalkApi.request (D) : notifyUpdated[lastRev=16,deviceInfo=DeviceInfo(applicationType:ANDROID_BETA, deviceName:SHV-E300S, systemName:Android OS, systemVersion:4.3, model:SHV-E300S, carrierCode:NOT_SPECIFIED, carrierName:45005)]
2015-08-19 19:56:06(pid=8149,tid=11295) : TalkApi.exception (D) : notifyUpdated
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.notifyUpdated(TalkServiceClient.java:3941)
	at jp.naver.line.android.DeviceInfoUpdater$1.run(DeviceInfoUpdater.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 19:56:19(pid=8149,tid=11277) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 19:56:19(pid=8149,tid=11277) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 19:59:57(pid=8149,tid=11277) : TalkApi.request (D) : updateNotificationToken[type=GOOGLE_GCM,token=APA91bGLLJrjHRLFE3L1baBwzpFilDiNgsMPPOIGUvn5Dku_97PlVDKB2kpr8kfg0i6_Q0kvVLisPrwKec8SDYg7Sy0YuLfm62R15PhkmVTQ_UG0lFuhUtbuhmGJU8UhIBHQY3OMnukqVC1xuQbRwCOGI-D2g7a7Ig]
2015-08-19 19:59:57(pid=8149,tid=11277) : TalkApi.exception (D) : updateNotificationToken
TalkException(code:INTERNAL_ERROR, reason:already received auth error., parameterMap:null)
	at jp.naver.line.android.thrift.client.TalkClient.getClient(TalkClient.java:46)
	at jp.naver.line.android.thrift.client.TalkServiceClient.updateNotificationToken(TalkServiceClient.java:6193)
	at jp.naver.line.android.service.push.PushTokenProxy$1.run(PushTokenProxy.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 20:18:59(pid=8149,tid=11274) : TalkApi.request (D) : fetchOps[localRev=16,count=100,globalRev=33872,individualRev=0]
2015-08-19 20:19:00(pid=8149,tid=11284) : TalkApi.request (D) : getProfileWithoutHandleException[]
2015-08-19 20:19:00(pid=8149,tid=11284) : TalkApi.exception (D) : RequestCallback[5](elapseTime=623ms)
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_fetchOps(TalkService.java:10514)
	at jp.naver.line.android.thrift.client.TalkServiceClient$1.getResponse(TalkServiceClient.java:1064)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:134)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 20:19:00(pid=8149,tid=11279) : TalkApi.request (D) : fetchOps[localRev=16,count=100,globalRev=33872,individualRev=0]
2015-08-19 20:19:03(pid=8149,tid=11281) : TalkApi.exception (D) : RequestCallback[6](elapseTime=3498ms)
TalkException(code:NOT_AUTHORIZED_DEVICE, reason:Auth Failed, parameterMap:{SUB_ERROR_CODE=DEVICE_LOSE})
	at jp.naver.talk.protocol.thriftv1.TalkService$Client.recv_getProfile(TalkService.java:5518)
	at jp.naver.line.android.thrift.client.TalkServiceClient$2.getResponse(TalkServiceClient.java:2801)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:134)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)

2015-08-19 20:19:03(pid=8149,tid=11284) : TalkApi.exception (D) : RequestCallback[7](elapseTime=2909ms)
jp.naver.line.android.thrift.TTransportResetConnectionException: jp.naver.line.android.legy.LegyResetConnectionException
	at jp.naver.line.android.thrift.LineTTransport.convertToTTransportException(LineTTransport.java:609)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:486)
	at jp.naver.line.android.thrift.LineTTransport$1.response(LineTTransport.java:393)
	at jp.naver.line.android.legy.LegyBaseRequestHandler$1.complete(LegyBaseRequestHandler.java:34)
	at jp.naver.line.android.legy.LegyRequest$ReceivedCompleteCallback.run(LegyRequest.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at jp.naver.line.android.util.ExecutorServiceBase$TaskWorker.run(ExecutorServiceBase.java:242)
	at java.lang.Thread.run(Thread.java:841)
Caused by: jp.naver.line.android.legy.LegyResetConnectionException
	at jp.naver.line.android.legy.spdy.LegySpdyChannelHandler.resetMember(LegySpdyChannelHandler.java:453)
	at jp.naver.line.android.legy.spdy.LegySpdySession$LegySpdyChannelPipelineFactory.resetMember(LegySpdySession.java:500)
	at jp.naver.line.android.legy.spdy.LegySpdySession.resetMember(LegySpdySession.java:86)
	at jp.naver.line.android.legy.LegySession.close(LegySession.java:358)
	at jp.naver.line.android.legy.LegySessionPool$CachedLegySession.closeSession(LegySessionPool.java:290)
	at jp.naver.line.android.legy.LegySessionPool.closeSpdySessions(LegySessionPool.java:105)
	at jp.naver.line.android.legy.LegySessionPool.closeAllSessions(LegySessionPool.java:41)
	at jp.naver.line.android.thrift.client.TalkClient$GetProfileCallback.failed(TalkClient.java:177)
	at jp.naver.line.android.thrift.client.TalkServiceClient$2.innerFailed(TalkServiceClient.java:2821)
	at jp.naver.line.android.thrift.client.TalkServiceClient$RequestCallback.success(TalkServiceClient.java:137)
	at jp.naver.line.android.thrift.LineTTransport$AsyncCallback.complete(LineTTransport.java:471)
	... 10 more

